apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
    name: helmargointegration
spec:
    project: default
    destination:
       server: https://kubernetes.default.svc
       namespace: default 
    source:
       helm:
          releaseName: apphelmargo
          parameters: 
            -  name: "replicaCount"
               value: "5"
       repoURL: https://github.com/ROHITkumaw/gitops_argocd.git
       path: helm/pracchart 
       targetRevision: main

